# Definição de um grupo chamado "terraform-ansible"
# Isso permite que várias máquinas sejam gerenciadas juntas pelo Ansible
[terraform-ansible]

# Endereço IP do servidor que será gerenciado pelo Ansible
# Esse IP deve ser acessível via SSH para que o Ansible funcione corretamente
35.91.228.132